### ISSUE TITLE
JSON error uninitialized constant OWMO::Weather::JSON (NameError)

### ISSUE THREAD

**Issue by Gizmokid2005** [robb-randall/owmo#9]
When trying to even run the [example code](https://github.com/robb-randall/owmo/blob/main/examples/current.rb) with my own api key, I receive a JSON NameError.

```
/home/gizmo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/owmo-2.1.0/lib/owmo/weather.rb:124:in `http_get': uninitialized constant OWMO::Weather::JSON (NameError)

      JSON.parse(response.weather)
      ^^^^
        from /home/gizmo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/owmo-2.1.0/lib/owmo/weather.rb:85:in `get'
        from wtest.rb:12:in `<main>'
```

If I also `require 'json'` in the file, I instead get the following HTTP error.

```
/home/gizmo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/owmo-2.1.0/lib/owmo/weather.rb:124:in `http_get': undefined method `weather' for #<Net::HTTPOK 200 OK readbody=true> (NoMethodError)

      JSON.parse(response.weather)
                         ^^^^^^^^
        from /home/gizmo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/owmo-2.1.0/lib/owmo/weather.rb:85:in `get'
        from wtest.rb:13:in `<main>'
```

This behavior seems to exist in both Ruby 3.2.0 as well as 2.6.10.

**Comment by robb-randall** [comment]
Thanks @Gizmokid2005 for trying that. I found some issues that I introduced when refactored earlier this month. Would you mind trying my latest PR (#10)?

**Comment by Gizmokid2005** [comment]
Hey @robb-randall - thanks for the quick reply! It looks like that should take care of it. I am getting (kind of) unexpected 404s, I suspect this is intended handling behavior but figured I'd call it out here just in case it isn't. (Thanks OWM for the weird requirement on searching.)
```
irb(main):003:0> OWMO::weather(apikey).get :current, q: "Atlanta, GA"
/home/gizmo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/owmo-2.1.0/lib/owmo/weather.rb:89:in `get': ERROR 404: Not Found (OWMO::Weather::WeatherResponseError)
        from (irb):3:in `<main>'
        from /home/gizmo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
        from /home/gizmo/.rbenv/versions/3.2.0/bin/irb:25:in `load'
        from /home/gizmo/.rbenv/versions/3.2.0/bin/irb:25:in `<main>'
irb(main):004:0> OWMO::weather(apikey).get :current, q: "Atlanta, GA, US"
=>
{"coord"=>{"lon"=>-84.388, "lat"=>33.749},
 "weather"=>[{"id"=>800, "main"=>"Clear", "description"=>"clear sky", "icon"=>"01d"}],
 "base"=>"stations",
 "main"=>{"temp"=>288.74, "feels_like"=>287.29, "temp_min"=>287.03, "temp_max"=>290.2, "pressure"=>1017, "humidity"=>36},
 "visibility"=>10000,
 "wind"=>{"speed"=>3.09, "deg"=>290},
 "clouds"=>{"all"=>0},
 "dt"=>1673381238,
 "sys"=>{"type"=>2, "id"=>2006620, "country"=>"US", "sunrise"=>1673354572, "sunset"=>1673390803},
 "timezone"=>-18000,
 "id"=>4180439,
 "name"=>"Atlanta",
 "cod"=>200}
```

**Comment by robb-randall** [comment]
Unfortunately, I'm receiving the same error. I'll need to dive deeper into this later. You can try an older version (v1.x) or submit a PR. Thanks again!

**Comment by Gizmokid2005** [comment]
I think it's mostly expected, looking at other gems and at the API, OWM just doesn't seem to enjoy <City, State> from US locations, it's probably genuinely returning some kind of error. It's not a showstopper for me, I was expecting this to be an issue and am planning on parsing to coordinates to prevent this issue as much as I can.
